name: swim_success_dev
description: "Pace selector with swimmer level detection and user list with detail screen."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.0

  # Navigation
  auto_route: ^9.2.2

  # DI
  get_it: ^8.0.2

  # Networking
  dio: ^5.8.0

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Logging
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  auto_route_generator: ^9.2.2

flutter:
  uses-material-design: true
